import './globals.css'
import Header from './/components/Header'
export const metadata = {
  title: 'web scraper with nextjs13 app router + typescript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900">
        <Header />
        <main>
         {children}
        </main>
        
      
      </body>
    </html>
  )
}
